experiment_project: 'WorldWander'
experiment_name: 'rank-80_stride-2_v1'
model_id: '/mnt/nfs/workspace/sqj/base_models/Wan2.2-TI2V-5B-Diffusers'
output_root: './outputs/wan2-2_three2one'
use_drop_text: True
use_lora: True
use_collaborative_position_encoding: True


training:
  resume_path: ~
  batch_size: 4
  max_steps: 8001
  warmup_steps: 10
  rank: 80
  learning_rate: 5e-5
  weight_decay: 1e-2
  save_val_interval_steps: 200
  accumulate_grad_batches: 1
  gradient_clip_val: ~
  precision: "bf16-mixed"
  accelerator: "auto"
  strategy: 'auto'
  gradient_checkpointing: True
  benchmark: False


dataset:
  first_video_root: '/mnt/nfs/workspace/sqj/EgoExoTrain/First_Video'
  third_video_root: '/mnt/nfs/workspace/sqj/EgoExoTrain/Third_Video'
  ref_image_root: '/mnt/nfs/workspace/sqj/EgoExoTrain/Reference_Image'
  is_one2three: False
  height: 704
  width: 1280
  sample_n_frames: 49
  stride: 2
  fps: 8
  num_workers: 8
  shuffle: True
  drop_last: True 
  pin_memory: True
